-- =======================================================
-- MIGRACIÓN A MYSQL - AnyOrder DATABASE (CORREGIDO)
-- =======================================================

-- Eliminar la base de datos si existe y crearla nuevamente
DROP DATABASE IF EXISTS AnyOrder;

CREATE DATABASE AnyOrder CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE AnyOrder;

-- =======================================================
-- NIVEL 1: TABLAS SIN DEPENDENCIAS
-- =======================================================

-- 1. AREAS
CREATE TABLE AREAS (
    ID_AREA INT AUTO_INCREMENT PRIMARY KEY,
    NAME_AREA VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPTION TEXT,
    STATE TINYINT(1) NOT NULL DEFAULT 1 CHECK (STATE IN (0, 1)),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_AREAS_NAME CHECK (
        CHAR_LENGTH(TRIM(NAME_AREA)) >= 2
    )
) ENGINE = InnoDB;

-- 2. ROLES
CREATE TABLE ROLES (
    ID_ROLE INT AUTO_INCREMENT PRIMARY KEY,
    NAME_ROLE VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPTION TEXT,
    ROLE_TYPE ENUM('EMPLOYEE', 'CUSTOMER') NOT NULL DEFAULT 'EMPLOYEE',
    -- Permisos específicos para clientes
    CAN_VIEW_MENU TINYINT(1) NOT NULL DEFAULT 1,
    CAN_PLACE_ORDERS TINYINT(1) NOT NULL DEFAULT 0,
    CAN_VIEW_PRICES TINYINT(1) NOT NULL DEFAULT 1,
    STATE TINYINT(1) NOT NULL DEFAULT 1 CHECK (STATE IN (0, 1)),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_ROLES_NAME CHECK (
        CHAR_LENGTH(TRIM(NAME_ROLE)) >= 2
    )
) ENGINE = InnoDB;

-- 3. PERMISSIONS
CREATE TABLE PERMISSIONS (
    ID_PERMISSION INT AUTO_INCREMENT PRIMARY KEY,
    NAME_PERMISSION VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPTION TEXT,
    STATE TINYINT(1) NOT NULL DEFAULT 1 CHECK (STATE IN (0, 1)),
    CONSTRAINT CHK_PERMISSIONS_NAME CHECK (
        CHAR_LENGTH(TRIM(NAME_PERMISSION)) >= 3
    )
) ENGINE = InnoDB;

-- 4. SUPPLIERS
CREATE TABLE SUPPLIERS (
    ID_SUPPLIER INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL,
    CONTACT_NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(150),
    ADDRESS VARCHAR(255) NOT NULL,
    DOCUMENT_TYPE ENUM('RUC', 'DNI', 'CEX') NOT NULL,
    DOCUMENT_NUMBER VARCHAR(20) NOT NULL UNIQUE,
    PAYMENT_TERMS VARCHAR(100),
    NOTES TEXT,
    STATE TINYINT(1) NOT NULL DEFAULT 1 CHECK (STATE IN (0, 1)),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_SUPPLIERS_NAME CHECK (CHAR_LENGTH(TRIM(NAME)) >= 3),
    CONSTRAINT CHK_SUPPLIERS_CONTACT CHECK (
        CHAR_LENGTH(TRIM(CONTACT_NAME)) >= 3
    ),
    CONSTRAINT CHK_SUPPLIERS_PHONE CHECK (CHAR_LENGTH(TRIM(PHONE)) >= 9),
    CONSTRAINT CHK_SUPPLIERS_EMAIL CHECK (
        EMAIL IS NULL
        OR EMAIL REGEXP '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'
    ),
    CONSTRAINT CHK_SUPPLIERS_DOCUMENT CHECK (
        CHAR_LENGTH(TRIM(DOCUMENT_NUMBER)) >= 8
    )
) ENGINE = InnoDB;

-- 5. CATEGORIES
CREATE TABLE CATEGORIES (
    ID_CATEGORY INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPTION TEXT,
    SECTION VARCHAR(100) NOT NULL,
    DELIVERY TINYINT(1) NOT NULL DEFAULT 0 CHECK (DELIVERY IN (0, 1)),
    DISPLAY_ORDER INT NOT NULL DEFAULT 0 CHECK (DISPLAY_ORDER >= 0),
    STATE TINYINT(1) NOT NULL DEFAULT 1 CHECK (STATE IN (0, 1)),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_CATEGORIES_NAME CHECK (CHAR_LENGTH(TRIM(NAME)) >= 2),
    CONSTRAINT CHK_CATEGORIES_SECTION CHECK (
        CHAR_LENGTH(TRIM(SECTION)) >= 2
    )
) ENGINE = InnoDB;

-- =======================================================
-- NIVEL 2: TABLAS QUE DEPENDEN DEL NIVEL 1
-- =======================================================

-- 6. ROLE_PERMISSIONS
CREATE TABLE ROLE_PERMISSIONS (
    ID_ROLE INT NOT NULL,
    ID_PERMISSION INT NOT NULL,
    PRIMARY KEY (ID_ROLE, ID_PERMISSION),
    CONSTRAINT FK_RP_ROLE FOREIGN KEY (ID_ROLE) REFERENCES ROLES (ID_ROLE) ON DELETE CASCADE,
    CONSTRAINT FK_RP_PERMISSION FOREIGN KEY (ID_PERMISSION) REFERENCES PERMISSIONS (ID_PERMISSION) ON DELETE CASCADE
) ENGINE = InnoDB;

-- 7. USERS
CREATE TABLE USERS (
    ID_USER INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    SURNAMES VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    DOCUMENT_NUMBER VARCHAR(20) NOT NULL UNIQUE,
    DOCUMENT_TYPE ENUM('DNI', 'CEX', 'PAS', 'RUC') NOT NULL,
    GENDER ENUM('M', 'F', 'O') DEFAULT NULL,
    PHONE VARCHAR(20) NOT NULL,
    ADRESS VARCHAR(255) NOT NULL,
    PROFILE_PHOTO VARCHAR(255),
    REGISTRATION_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATE TINYINT(1) NOT NULL DEFAULT 1 CHECK (STATE IN (0, 1)),
    ID_ROLE INT NOT NULL,
    ID_AREA INT NOT NULL,
    HORA_INICIO TIME NOT NULL,
    HORA_FIN TIME NOT NULL,
    PLANNED_HOURS DECIMAL(4, 2) NOT NULL CHECK (
        PLANNED_HOURS > 0
        AND PLANNED_HOURS <= 24
    ),
    TURNO VARCHAR(50) NOT NULL,
    HOURLY_RATE DECIMAL(10, 2) NOT NULL DEFAULT 0.00 CHECK (HOURLY_RATE >= 0),
    CONSTRAINT FK_USERS_AREA FOREIGN KEY (ID_AREA) REFERENCES AREAS (ID_AREA),
    CONSTRAINT FK_USERS_ROLE FOREIGN KEY (ID_ROLE) REFERENCES ROLES (ID_ROLE),
    CONSTRAINT CHK_USERS_NAME CHECK (CHAR_LENGTH(TRIM(NAME)) >= 2),
    CONSTRAINT CHK_USERS_SURNAMES CHECK (
        CHAR_LENGTH(TRIM(SURNAMES)) >= 2
    ),
    CONSTRAINT CHK_USERS_EMAIL CHECK (
        EMAIL REGEXP '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'
    ),
    CONSTRAINT CHK_USERS_PASSWORD CHECK (CHAR_LENGTH(PASSWORD) >= 6),
    CONSTRAINT CHK_USERS_DOCUMENT CHECK (
        CHAR_LENGTH(TRIM(DOCUMENT_NUMBER)) >= 8
    ),
    CONSTRAINT CHK_USERS_PHONE CHECK (CHAR_LENGTH(TRIM(PHONE)) >= 9),
    CONSTRAINT CHK_USERS_TURNO CHECK (CHAR_LENGTH(TRIM(TURNO)) >= 3),
    CONSTRAINT CHK_USERS_HOURS CHECK (HORA_FIN > HORA_INICIO)
) ENGINE = InnoDB;

-- 8. CUSTOMERS
CREATE TABLE CUSTOMERS (
    ID_CUSTOMER INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150),
    PASSWORD VARCHAR(255),
    PHONE VARCHAR(20) NOT NULL,
    DOCUMENT_TYPE ENUM('DNI', 'CEX', 'PAS', 'RUC') NOT NULL,
    DOCUMENT_NUMBER VARCHAR(20) NOT NULL UNIQUE,
    ADDRESS VARCHAR(255),
    CUSTOMER_TYPE ENUM('NATURAL', 'JURIDICO') NOT NULL DEFAULT 'NATURAL',
    ID_ROLE INT NOT NULL,
    LAST_PURCHASE_DATE DATETIME,
    TOTAL_PURCHASES INT NOT NULL DEFAULT 0 CHECK (TOTAL_PURCHASES >= 0),
    TOTAL_SPENT DECIMAL(12, 2) NOT NULL DEFAULT 0 CHECK (TOTAL_SPENT >= 0),
    STATE TINYINT(1) NOT NULL DEFAULT 1 CHECK (STATE IN (0, 1)),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CUSTOMERS_ROLE FOREIGN KEY (ID_ROLE) REFERENCES ROLES (ID_ROLE),
    CONSTRAINT CHK_CUSTOMERS_FNAME CHECK (
        CHAR_LENGTH(TRIM(FIRST_NAME)) >= 2
    ),
    CONSTRAINT CHK_CUSTOMERS_LNAME CHECK (
        CHAR_LENGTH(TRIM(LAST_NAME)) >= 2
    ),
    CONSTRAINT CHK_CUSTOMERS_PHONE CHECK (CHAR_LENGTH(TRIM(PHONE)) >= 9),
    CONSTRAINT CHK_CUSTOMERS_DOCUMENT CHECK (
        CHAR_LENGTH(TRIM(DOCUMENT_NUMBER)) >= 8
    )
) ENGINE = InnoDB;

-- 9. PRODUCTS
CREATE TABLE PRODUCTS (
    ID_PRODUCT INT AUTO_INCREMENT PRIMARY KEY,
    ID_CATEGORY INT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    ID_AREA INT NOT NULL,
    STATE TINYINT(1) NOT NULL DEFAULT 1 CHECK (STATE IN (0, 1)),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_PRODUCT_NAME_CAT UNIQUE (ID_CATEGORY, NAME),
    CONSTRAINT FK_PRODUCTS_CATEGORY FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORIES (ID_CATEGORY),
    CONSTRAINT FK_PRODUCTS_AREA FOREIGN KEY (ID_AREA) REFERENCES AREAS (ID_AREA),
    CONSTRAINT CHK_PRODUCTS_NAME CHECK (CHAR_LENGTH(TRIM(NAME)) >= 2)
) ENGINE = InnoDB;

-- 10. INGREDIENTS
CREATE TABLE INGREDIENTS (
    ID_INGREDIENT INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CODE VARCHAR(50) NOT NULL UNIQUE,
    CATEGORY VARCHAR(50) NOT NULL,
    UNIT VARCHAR(20) NOT NULL,
    QUANTITY DECIMAL(10, 2) NOT NULL DEFAULT 0 CHECK (QUANTITY >= 0),
    MIN_STOCK DECIMAL(10, 2) NOT NULL DEFAULT 0 CHECK (MIN_STOCK >= 0),
    UNIT_PRICE DECIMAL(10, 2) NOT NULL DEFAULT 0 CHECK (UNIT_PRICE >= 0),
    ID_SUPPLIER INT NOT NULL,
    EXPIRATION_DATE DATE,
    DESCRIPTION TEXT,
    STATE TINYINT(1) NOT NULL DEFAULT 1 CHECK (STATE IN (0, 1)),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_INGREDIENTS_SUPPLIER FOREIGN KEY (ID_SUPPLIER) REFERENCES SUPPLIERS (ID_SUPPLIER),
    CONSTRAINT CHK_INGREDIENTS_NAME CHECK (CHAR_LENGTH(TRIM(NAME)) >= 2),
    CONSTRAINT CHK_INGREDIENTS_CODE CHECK (CHAR_LENGTH(TRIM(CODE)) >= 2),
    CONSTRAINT CHK_INGREDIENTS_CATEGORY CHECK (
        CHAR_LENGTH(TRIM(CATEGORY)) >= 2
    ),
    CONSTRAINT CHK_INGREDIENTS_UNIT CHECK (CHAR_LENGTH(TRIM(UNIT)) >= 1)
) ENGINE = InnoDB;

-- 11. TABLES
CREATE TABLE TABLES (
    ID_TABLE INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE,
    ID_AREA INT NOT NULL,
    CAPACITY INT NOT NULL CHECK (
        CAPACITY > 0
        AND CAPACITY <= 50
    ),
    CURRENT_OCCUPANCY INT NOT NULL DEFAULT 0 CHECK (CURRENT_OCCUPANCY >= 0),
    LOCATION VARCHAR(50) NOT NULL,
    QR_CODE VARCHAR(255) UNIQUE,
    QR_TOKEN VARCHAR(100) UNIQUE,
    STATE TINYINT(1) NOT NULL DEFAULT 1 CHECK (STATE IN (0, 1)),
    IS_OCCUPIED TINYINT(1) NOT NULL DEFAULT 0 CHECK (IS_OCCUPIED IN (0, 1)),
    OCCUPIED_SINCE DATETIME,
    CONSTRAINT CHK_OCCUPANCY CHECK (CURRENT_OCCUPANCY <= CAPACITY),
    CONSTRAINT CHK_TABLES_NAME CHECK (CHAR_LENGTH(TRIM(NAME)) >= 2),
    CONSTRAINT CHK_TABLES_LOCATION CHECK (
        CHAR_LENGTH(TRIM(LOCATION)) >= 2
    ),
    CONSTRAINT FK_TABLES_AREA FOREIGN KEY (ID_AREA) REFERENCES AREAS (ID_AREA) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE = InnoDB;

-- =======================================================
-- NIVEL 3: TABLAS QUE DEPENDEN DEL NIVEL 2
-- =======================================================

-- 12. USER_LOGS
CREATE TABLE USER_LOGS (
    ID_LOG INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER INT NOT NULL,
    FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    HORA_ENTRADA DATETIME NOT NULL,
    HORA_SALIDA DATETIME,
    HOURS_WORKED DECIMAL(4, 2) CHECK (
        HOURS_WORKED >= 0
        AND HOURS_WORKED <= 24
    ),
    HOURLY_RATE DECIMAL(10, 2) NOT NULL CHECK (HOURLY_RATE >= 0),
    PLANNED_HOURS DECIMAL(4, 2) NOT NULL CHECK (PLANNED_HOURS > 0),
    STATE TINYINT(1) NOT NULL DEFAULT 1 CHECK (STATE IN (0, 1, 2)),
    CONSTRAINT FK_LOGS_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER),
    CONSTRAINT CHK_VALID_HOURS CHECK (
        HORA_SALIDA IS NULL
        OR HORA_SALIDA >= HORA_ENTRADA
    )
) ENGINE = InnoDB;

-- 13. PRESENTATIONS
CREATE TABLE PRESENTATIONS (
    ID_PRESENTATION INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUCT INT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT,
    COST DECIMAL(10, 2) NOT NULL DEFAULT 0 CHECK (COST >= 0),
    PRICE DECIMAL(10, 2) NOT NULL CHECK (PRICE >= 0),
    DELIVERY_PRICE DECIMAL(10, 2) CHECK (DELIVERY_PRICE >= 0),
    TAKEOUT_PRICE DECIMAL(10, 2) CHECK (TAKEOUT_PRICE >= 0),
    PROMO_PRICE DECIMAL(10, 2) CHECK (PROMO_PRICE >= 0),
    PREPARATION_TIME INT NOT NULL DEFAULT 0 CHECK (
        PREPARATION_TIME >= 0
        AND PREPARATION_TIME <= 180
    ),
    DISH_PHOTO_URL VARCHAR(500),
    STATE TINYINT(1) NOT NULL DEFAULT 1 CHECK (STATE IN (0, 1)),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PRESENTATIONS_PRODUCT FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS (ID_PRODUCT),
    CONSTRAINT CHK_PRESENTATIONS_NAME CHECK (CHAR_LENGTH(TRIM(NAME)) >= 2),
    CONSTRAINT CHK_PRESENTATIONS_PRICE CHECK (PRICE >= COST)
) ENGINE = InnoDB;

-- 14. PURCHASE_ORDERS
CREATE TABLE PURCHASE_ORDERS (
    ID_PURCHASE_ORDER INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    ID_SUPPLIER INT NOT NULL,
    ID_USER INT NOT NULL,
    ORDER_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELIVERY_DATE DATE NOT NULL,
    RECEIVED_DATE DATETIME,
    TOTAL DECIMAL(12, 2) NOT NULL CHECK (TOTAL >= 0),
    ORDER_STATUS ENUM(
        'PENDIENTE',
        'CONFIRMADO',
        'EN_TRANSITO',
        'RECIBIDO',
        'CANCELADO'
    ) NOT NULL DEFAULT 'PENDIENTE',
    PAYMENT_STATUS ENUM(
        'PENDIENTE',
        'PAGADO_PARCIAL',
        'PAGADO_COMPLETO'
    ) NOT NULL DEFAULT 'PENDIENTE',
    NOTES TEXT,
    STATE TINYINT(1) NOT NULL DEFAULT 1 CHECK (STATE IN (0, 1)),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PO_SUPPLIER FOREIGN KEY (ID_SUPPLIER) REFERENCES SUPPLIERS (ID_SUPPLIER),
    CONSTRAINT FK_PO_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER),
    CONSTRAINT CHK_PO_NUMBER CHECK (
        CHAR_LENGTH(TRIM(ORDER_NUMBER)) >= 3
    ),
    CONSTRAINT CHK_PO_DELIVERY CHECK (
        DELIVERY_DATE >= DATE(ORDER_DATE)
    ),
    CONSTRAINT CHK_PO_RECEIVED CHECK (
        RECEIVED_DATE IS NULL
        OR RECEIVED_DATE >= ORDER_DATE
    )
) ENGINE = InnoDB;

-- 15. INVENTORY_MOVEMENTS
CREATE TABLE INVENTORY_MOVEMENTS (
    ID_MOVEMENT INT AUTO_INCREMENT PRIMARY KEY,
    ID_INGREDIENT INT NOT NULL,
    MOVEMENT_TYPE ENUM(
        'ENTRADA',
        'SALIDA',
        'AJUSTE',
        'MERMA',
        'DEVOLUCION'
    ) NOT NULL,
    QUANTITY DECIMAL(10, 2) NOT NULL CHECK (QUANTITY != 0),
    PREVIOUS_STOCK DECIMAL(10, 2) NOT NULL CHECK (PREVIOUS_STOCK >= 0),
    NEW_STOCK DECIMAL(10, 2) NOT NULL CHECK (NEW_STOCK >= 0),
    UNIT_COST DECIMAL(10, 2) CHECK (UNIT_COST >= 0),
    TOTAL_COST DECIMAL(12, 2) CHECK (TOTAL_COST >= 0),
    REASON VARCHAR(255) NOT NULL,
    ID_USER INT NOT NULL,
    MOVEMENT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NOTES TEXT,
    CONSTRAINT FK_IM_INGREDIENT FOREIGN KEY (ID_INGREDIENT) REFERENCES INGREDIENTS (ID_INGREDIENT),
    CONSTRAINT FK_IM_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER),
    CONSTRAINT CHK_IM_REASON CHECK (
        CHAR_LENGTH(TRIM(REASON)) >= 3
    )
) ENGINE = InnoDB;

-- 16. RESERVATIONS
CREATE TABLE RESERVATIONS (
    ID_RESERVATION INT AUTO_INCREMENT PRIMARY KEY,
    ID_CUSTOMER INT NOT NULL,
    ID_TABLE INT NOT NULL,
    RESERVATION_DATE DATETIME NOT NULL,
    NUMBER_OF_PEOPLE INT NOT NULL CHECK (
        NUMBER_OF_PEOPLE > 0
        AND NUMBER_OF_PEOPLE <= 50
    ),
    CUSTOMER_NAME VARCHAR(200) NOT NULL,
    CUSTOMER_PHONE VARCHAR(20) NOT NULL,
    SPECIAL_REQUESTS TEXT,
    RESERVATION_STATUS ENUM(
        'PENDIENTE',
        'CONFIRMADA',
        'CANCELADA',
        'COMPLETADA',
        'NO_SHOW'
    ) NOT NULL DEFAULT 'PENDIENTE',
    CREATED_BY INT NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NOTES TEXT,
    CONSTRAINT FK_RES_CUSTOMER FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMERS (ID_CUSTOMER),
    CONSTRAINT FK_RES_TABLE FOREIGN KEY (ID_TABLE) REFERENCES TABLES (ID_TABLE),
    CONSTRAINT FK_RES_USER FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID_USER),
    CONSTRAINT CHK_RES_NAME CHECK (
        CHAR_LENGTH(TRIM(CUSTOMER_NAME)) >= 3
    ),
    CONSTRAINT CHK_RES_PHONE CHECK (
        CHAR_LENGTH(TRIM(CUSTOMER_PHONE)) >= 9
    ),
    CONSTRAINT CHK_RES_DATE CHECK (
        RESERVATION_DATE >= CREATED_AT
    )
) ENGINE = InnoDB;

-- 17. QR_SESSIONS
CREATE TABLE QR_SESSIONS (
    ID_SESSION INT AUTO_INCREMENT PRIMARY KEY,
    ID_TABLE INT NOT NULL,
    ID_CUSTOMER INT,
    SESSION_TOKEN VARCHAR(100) NOT NULL UNIQUE,
    CUSTOMER_NAME VARCHAR(100), -- Para clientes anónimos o como respaldo
    NUMBER_OF_PEOPLE INT NOT NULL DEFAULT 1 CHECK (
        NUMBER_OF_PEOPLE > 0
        AND NUMBER_OF_PEOPLE <= 50
    ),
    SESSION_STATUS ENUM(
        'ACTIVA',
        'CERRADA',
        'EXPIRADA'
    ) NOT NULL DEFAULT 'ACTIVA',
    STARTED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CLOSED_AT DATETIME,
    EXPIRES_AT DATETIME,
    CONSTRAINT FK_QRS_TABLE FOREIGN KEY (ID_TABLE) REFERENCES TABLES (ID_TABLE),
    CONSTRAINT FK_QRS_CUSTOMER FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMERS (ID_CUSTOMER), --
    CONSTRAINT CHK_QRS_TOKEN CHECK (
        CHAR_LENGTH(TRIM(SESSION_TOKEN)) >= 10
    ),
    CONSTRAINT CHK_QRS_CLOSE CHECK (
        CLOSED_AT IS NULL
        OR CLOSED_AT >= STARTED_AT
    )
) ENGINE = InnoDB;
-- 18. ORDERS
CREATE TABLE ORDERS (
    ID_ORDER INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER INT NOT NULL,
    ID_CUSTOMER INT,
    ORDER_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ORDER_STATUS ENUM(
        'PENDIENTE',
        'EN_PREPARACION',
        'LISTO',
        'ENTREGADO',
        'CERRADO',
        'CANCELADO'
    ) NOT NULL,
    TYPE_OF_CONSUMPTION ENUM(
        'LOCAL',
        'DELIVERY',
        'TAKEOUT',
        'PROMO'
    ) NOT NULL,
    ID_TABLE INT,
    TOTAL DECIMAL(10, 2) NOT NULL CHECK (TOTAL >= 0),
    TOTAL_ITEMS INT NOT NULL CHECK (
        TOTAL_ITEMS >= 0
        AND TOTAL_ITEMS <= 500
    ),
    NUMBER_OF_PEOPLE INT NOT NULL DEFAULT 1 CHECK (
        NUMBER_OF_PEOPLE > 0
        AND NUMBER_OF_PEOPLE <= 50
    ),
    DELIVERY_ADDRESS VARCHAR(255),
    CUSTOMER_NOTES TEXT,
    CONFIRMED TINYINT(1) NOT NULL DEFAULT 0 CHECK (CONFIRMED IN (0, 1)),
    CONSTRAINT FK_ORDERS_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER),
    CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMERS (ID_CUSTOMER),
    CONSTRAINT FK_ORDERS_TABLE FOREIGN KEY (ID_TABLE) REFERENCES TABLES (ID_TABLE),
    CONSTRAINT CHK_DELIVERY_ADDRESS CHECK (
        (
            TYPE_OF_CONSUMPTION = 'DELIVERY'
            AND DELIVERY_ADDRESS IS NOT NULL
            AND CHAR_LENGTH(TRIM(DELIVERY_ADDRESS)) >= 10
        )
        OR (
            TYPE_OF_CONSUMPTION != 'DELIVERY'
        )
    ),
    CONSTRAINT CHK_TABLE_LOCAL CHECK (
        (
            TYPE_OF_CONSUMPTION = 'LOCAL'
            AND ID_TABLE IS NOT NULL
        )
        OR (
            TYPE_OF_CONSUMPTION != 'LOCAL'
        )
    )
) ENGINE = InnoDB;

-- =======================================================
-- NIVEL 4: TABLAS QUE DEPENDEN DEL NIVEL 3
-- =======================================================

-- 19. PRESENTATION_INGREDIENTS
CREATE TABLE PRESENTATION_INGREDIENTS (
    ID_PRESENTATION INT NOT NULL,
    ID_INGREDIENT INT NOT NULL,
    QUANTITY DECIMAL(10, 2) NOT NULL CHECK (
        QUANTITY > 0
        AND QUANTITY <= 10000
    ),
    UNIT VARCHAR(20) NOT NULL,
    NOTES TEXT,
    PRIMARY KEY (
        ID_PRESENTATION,
        ID_INGREDIENT
    ),
    CONSTRAINT FK_PI_PRESENTATION FOREIGN KEY (ID_PRESENTATION) REFERENCES PRESENTATIONS (ID_PRESENTATION) ON DELETE CASCADE,
    CONSTRAINT FK_PI_INGREDIENT FOREIGN KEY (ID_INGREDIENT) REFERENCES INGREDIENTS (ID_INGREDIENT),
    CONSTRAINT CHK_PI_UNIT CHECK (CHAR_LENGTH(TRIM(UNIT)) >= 1)
) ENGINE = InnoDB;

-- 20. PURCHASE_ORDER_DETAILS
CREATE TABLE PURCHASE_ORDER_DETAILS (
    ID_DETAIL INT AUTO_INCREMENT PRIMARY KEY,
    ID_PURCHASE_ORDER INT NOT NULL,
    ID_INGREDIENT INT NOT NULL,
    QUANTITY DECIMAL(10, 2) NOT NULL CHECK (
        QUANTITY > 0
        AND QUANTITY <= 100000
    ),
    UNIT_PRICE DECIMAL(10, 2) NOT NULL CHECK (UNIT_PRICE >= 0),
    SUBTOTAL DECIMAL(12, 2) NOT NULL CHECK (SUBTOTAL >= 0),
    RECEIVED_QUANTITY DECIMAL(10, 2) NOT NULL DEFAULT 0 CHECK (RECEIVED_QUANTITY >= 0),
    CONSTRAINT FK_POD_ORDER FOREIGN KEY (ID_PURCHASE_ORDER) REFERENCES PURCHASE_ORDERS (ID_PURCHASE_ORDER) ON DELETE CASCADE,
    CONSTRAINT FK_POD_INGREDIENT FOREIGN KEY (ID_INGREDIENT) REFERENCES INGREDIENTS (ID_INGREDIENT),
    CONSTRAINT CHK_POD_RECEIVED CHECK (RECEIVED_QUANTITY <= QUANTITY)
) ENGINE = InnoDB;

-- 21. QR_ORDERS
CREATE TABLE QR_ORDERS (
    ID_QR_ORDER INT AUTO_INCREMENT PRIMARY KEY,
    ID_SESSION INT NOT NULL,
    ID_PRESENTATION INT NOT NULL,
    AMOUNT INT NOT NULL CHECK (
        AMOUNT > 0
        AND AMOUNT <= 100
    ),
    UNIT_PRICE DECIMAL(10, 2) NOT NULL CHECK (UNIT_PRICE >= 0),
    SUBTOTAL DECIMAL(12, 2) NOT NULL CHECK (SUBTOTAL >= 0),
    NOTES TEXT,
    ORDER_STATUS ENUM(
        'PENDIENTE',
        'CONFIRMADO',
        'CANCELADO'
    ) NOT NULL DEFAULT 'PENDIENTE',
    CONFIRMED_BY INT,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONFIRMED_AT DATETIME,
    CONSTRAINT FK_QRO_SESSION FOREIGN KEY (ID_SESSION) REFERENCES QR_SESSIONS (ID_SESSION) ON DELETE CASCADE,
    CONSTRAINT FK_QRO_PRESENTATION FOREIGN KEY (ID_PRESENTATION) REFERENCES PRESENTATIONS (ID_PRESENTATION),
    CONSTRAINT FK_QRO_USER FOREIGN KEY (CONFIRMED_BY) REFERENCES USERS (ID_USER),
    CONSTRAINT CHK_QRO_CONFIRM CHECK (
        CONFIRMED_AT IS NULL
        OR CONFIRMED_AT >= CREATED_AT
    )
) ENGINE = InnoDB;

-- 22. ORDER_DETAILS
CREATE TABLE ORDER_DETAILS (
    ID_DETAIL INT AUTO_INCREMENT PRIMARY KEY,
    ID_ORDER INT NOT NULL,
    ID_PRESENTATION INT NOT NULL,
    AMOUNT INT NOT NULL CHECK (
        AMOUNT > 0
        AND AMOUNT <= 100
    ),
    UNIT_PRICE DECIMAL(10, 2) NOT NULL CHECK (UNIT_PRICE >= 0),
    SUBTOTAL DECIMAL(12, 2) NOT NULL CHECK (SUBTOTAL >= 0),
    NOTES TEXT,
    CONSTRAINT FK_OD_ORDER FOREIGN KEY (ID_ORDER) REFERENCES ORDERS (ID_ORDER) ON DELETE CASCADE,
    CONSTRAINT FK_OD_PRESENTATION FOREIGN KEY (ID_PRESENTATION) REFERENCES PRESENTATIONS (ID_PRESENTATION)
) ENGINE = InnoDB;

-- 23. SALES
CREATE TABLE SALES (
    ID_SALE INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER INT NOT NULL,
    ID_ORDER INT NOT NULL,
    ID_CUSTOMER INT,
    SALE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATE TINYINT(1) NOT NULL DEFAULT 2 CHECK (STATE IN (0, 1, 2)),
    CONSTRAINT FK_SALES_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER),
    CONSTRAINT FK_SALES_CUSTOMER FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMERS (ID_CUSTOMER),
    CONSTRAINT FK_SALES_ORDER FOREIGN KEY (ID_ORDER) REFERENCES ORDERS (ID_ORDER)
) ENGINE = InnoDB;

-- =======================================================
-- NIVEL 5: TABLAS QUE DEPENDEN DEL NIVEL 4
-- =======================================================

-- 24. SALE_PAYMENTS
CREATE TABLE SALE_PAYMENTS (
    ID_PAYMENT INT AUTO_INCREMENT PRIMARY KEY,
    ID_SALE INT NOT NULL,
    PAYMENT_TYPE ENUM(
        'EFECTIVO',
        'TARJETA',
        'YAPE',
        'PLIN',
        'TRANSFERENCIA'
    ) NOT NULL,
    AMOUNT DECIMAL(10, 2) NOT NULL CHECK (AMOUNT > 0),
    CASH_RECEIVED DECIMAL(10, 2),
    CASH_CHANGE DECIMAL(10, 2) CHECK (CASH_CHANGE >= 0),
    CARD_TYPE VARCHAR(20),
    CARD_LAST4 VARCHAR(4),
    CARD_OPERATION VARCHAR(50),
    POS_REFERENCE VARCHAR(50),
    PHONE_PAYMENT VARCHAR(20),
    TRANSACTION_CODE VARCHAR(50),
    BANK_NAME VARCHAR(50),
    BANK_ACCOUNT VARCHAR(30),
    BANK_OPERATION VARCHAR(50),
    PAYMENT_PROOF_URL VARCHAR(500),
    PAYMENT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SP_SALE FOREIGN KEY (ID_SALE) REFERENCES SALES (ID_SALE) ON DELETE CASCADE,
    CONSTRAINT CHK_SP_CARD_LAST4 CHECK (
        CARD_LAST4 IS NULL
        OR CHAR_LENGTH(CARD_LAST4) = 4
    ),
    CONSTRAINT CHK_SP_PHONE CHECK (
        PHONE_PAYMENT IS NULL
        OR CHAR_LENGTH(TRIM(PHONE_PAYMENT)) >= 9
    ),
    CONSTRAINT CHK_SP_CASH_RECEIVED CHECK (
        CASH_RECEIVED IS NULL
        OR CASH_RECEIVED >= AMOUNT
    ),
    CONSTRAINT CHK_SP_CASH CHECK (
        (
            PAYMENT_TYPE = 'EFECTIVO'
            AND CASH_RECEIVED IS NOT NULL
        )
        OR (PAYMENT_TYPE != 'EFECTIVO')
    )
) ENGINE = InnoDB;

-- 25. DETAIL_SALE
CREATE TABLE DETAIL_SALE (
    ID_DETAIL INT AUTO_INCREMENT PRIMARY KEY,
    ID_SALE INT NOT NULL,
    ID_PRESENTATION INT NOT NULL,
    AMOUNT INT NOT NULL CHECK (
        AMOUNT > 0
        AND AMOUNT <= 100
    ),
    UNIT_PRICE DECIMAL(10, 2) NOT NULL CHECK (UNIT_PRICE >= 0),
    SUBTOTAL DECIMAL(12, 2) NOT NULL CHECK (SUBTOTAL >= 0),
    CONSTRAINT FK_DS_SALE FOREIGN KEY (ID_SALE) REFERENCES SALES (ID_SALE) ON DELETE CASCADE,
    CONSTRAINT FK_DS_PRESENTATION FOREIGN KEY (ID_PRESENTATION) REFERENCES PRESENTATIONS (ID_PRESENTATION)
) ENGINE = InnoDB;

-- =======================================================
-- REGLAS DE NEGOCIO, AUTOMATIZACIONES Y REPORTES
-- =======================================================

-- Indices operativos para pantallas de restaurante en tiempo real
CREATE INDEX IDX_USERS_STATE_ROLE ON USERS (STATE, ID_ROLE);
CREATE INDEX IDX_TABLES_AREA_STATE_OCCUPIED ON TABLES (ID_AREA, STATE, IS_OCCUPIED);
CREATE INDEX IDX_INGREDIENTS_STOCK_ALERT ON INGREDIENTS (STATE, QUANTITY, MIN_STOCK, EXPIRATION_DATE);
CREATE INDEX IDX_ORDERS_STATUS_DATE ON ORDERS (ORDER_STATUS, ORDER_DATE);
CREATE INDEX IDX_ORDERS_TABLE_STATUS ON ORDERS (ID_TABLE, ORDER_STATUS);
CREATE INDEX IDX_ORDER_DETAILS_ORDER ON ORDER_DETAILS (ID_ORDER);
CREATE INDEX IDX_SALES_DATE_STATE ON SALES (SALE_DATE, STATE);
CREATE INDEX IDX_RESERVATIONS_TABLE_DATE_STATUS ON RESERVATIONS (ID_TABLE, RESERVATION_DATE, RESERVATION_STATUS);
CREATE INDEX IDX_QR_SESSIONS_TABLE_STATUS ON QR_SESSIONS (ID_TABLE, SESSION_STATUS);
CREATE INDEX IDX_PURCHASES_STATUS_DELIVERY ON PURCHASE_ORDERS (ORDER_STATUS, DELIVERY_DATE);

-- Vistas para tableros y alertas del negocio
CREATE OR REPLACE VIEW VW_INVENTORY_ALERTS AS
SELECT
    I.ID_INGREDIENT,
    I.NAME,
    I.CODE,
    I.CATEGORY,
    I.UNIT,
    I.QUANTITY,
    I.MIN_STOCK,
    I.EXPIRATION_DATE,
    CASE
        WHEN I.EXPIRATION_DATE IS NOT NULL AND I.EXPIRATION_DATE < CURRENT_DATE THEN 'VENCIDO'
        WHEN I.EXPIRATION_DATE IS NOT NULL AND I.EXPIRATION_DATE <= DATE_ADD(CURRENT_DATE, INTERVAL 7 DAY) THEN 'POR_VENCER'
        WHEN I.QUANTITY <= I.MIN_STOCK THEN 'STOCK_BAJO'
        ELSE 'OK'
    END AS ALERT_TYPE
FROM INGREDIENTS I
WHERE I.STATE = 1
  AND (
      I.QUANTITY <= I.MIN_STOCK
      OR (I.EXPIRATION_DATE IS NOT NULL AND I.EXPIRATION_DATE <= DATE_ADD(CURRENT_DATE, INTERVAL 7 DAY))
  );

CREATE OR REPLACE VIEW VW_TABLES_REAL_TIME AS
SELECT
    T.ID_TABLE,
    T.NAME,
    A.NAME_AREA,
    T.CAPACITY,
    T.CURRENT_OCCUPANCY,
    T.IS_OCCUPIED,
    T.OCCUPIED_SINCE,
    CASE
        WHEN T.STATE = 0 THEN 'INACTIVA'
        WHEN T.IS_OCCUPIED = 1 THEN 'OCUPADA'
        ELSE 'LIBRE'
    END AS TABLE_STATUS
FROM TABLES T
JOIN AREAS A ON A.ID_AREA = T.ID_AREA;

CREATE OR REPLACE VIEW VW_KITCHEN_QUEUE AS
SELECT
    O.ID_ORDER,
    O.ORDER_DATE,
    O.ORDER_STATUS,
    O.TYPE_OF_CONSUMPTION,
    T.NAME AS TABLE_NAME,
    A.NAME_AREA,
    O.TOTAL_ITEMS,
    O.TOTAL,
    TIMESTAMPDIFF(MINUTE, O.ORDER_DATE, CURRENT_TIMESTAMP) AS WAIT_MINUTES
FROM ORDERS O
LEFT JOIN TABLES T ON T.ID_TABLE = O.ID_TABLE
LEFT JOIN AREAS A ON A.ID_AREA = T.ID_AREA
WHERE O.ORDER_STATUS IN ('PENDIENTE', 'EN_PREPARACION', 'LISTO');

CREATE OR REPLACE VIEW VW_DAILY_SALES_SUMMARY AS
SELECT
    DATE(S.SALE_DATE) AS SALE_DAY,
    COUNT(*) AS SALES_COUNT,
    SUM(S.TOTAL) AS GROSS_TOTAL,
    SUM(CASE WHEN S.STATE = 1 THEN S.TOTAL ELSE 0 END) AS NET_TOTAL,
    SUM(CASE WHEN S.STATE = 0 THEN S.TOTAL ELSE 0 END) AS ANNULLED_TOTAL
FROM SALES S
GROUP BY DATE(S.SALE_DATE);

CREATE OR REPLACE VIEW VW_TOP_PRESENTATIONS AS
SELECT
    P.ID_PRESENTATION,
    PR.NAME AS PRODUCT_NAME,
    P.NAME AS PRESENTATION_NAME,
    SUM(DS.AMOUNT) AS UNITS_SOLD,
    SUM(DS.SUBTOTAL) AS TOTAL_SOLD
FROM DETAIL_SALE DS
JOIN SALES S ON S.ID_SALE = DS.ID_SALE AND S.STATE = 1
JOIN PRESENTATIONS P ON P.ID_PRESENTATION = DS.ID_PRESENTATION
JOIN PRODUCTS PR ON PR.ID_PRODUCT = P.ID_PRODUCT
GROUP BY P.ID_PRESENTATION, PR.NAME, P.NAME
ORDER BY UNITS_SOLD DESC, TOTAL_SOLD DESC;

-- Nota de despliegue:
-- No se crean TRIGGERS en este script porque muchos servidores MySQL con
-- binary logging activo rechazan CREATE TRIGGER para usuarios sin SUPER.
-- Las reglas cruzadas se mantienen en el backend Spring:
-- - una sesion QR activa por mesa
-- - reservas no solapadas
-- - un turno activo por usuario
-- - cobro solo de pedidos ENTREGADOS
-- - una venta vigente por pedido
-- - calculo de subtotales y vuelto
