spring:
  application:
    name: AnyOrder

  main:
    banner-mode: console
    log-startup-info: false

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/AnyOrder?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true}
    username: ${DB_USER:root}
    password: ${DB_PASS:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 1
      connection-timeout: 3000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
      indent-output: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

# Configuración de servicios externos
external:
  api:
    token: ${EXTERNAL_API_TOKEN:none}
    reniec:
      url: ${RENIEC_API_URL:https://api.apis.net.pe/v2/reniec/dni}
    sunat:
      url: ${SUNAT_API_URL:https://api.apis.net.pe/v2/sunat/ruc}
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME:none}
    api-key: ${CLOUDINARY_API_KEY:none}
    api-secret: ${CLOUDINARY_API_SECRET:none}

server:
  port: ${PORT:8080}

logging:
  level:
    root: ERROR
    "[com.anyorder.pos.anyorder]": INFO